version: '3.1'

services:
  ote-mysql-db:
    image: mysql:8.0
    container_name: ote-learning-container
    network_mode: bridge
    environment:
      MYSQL_DATABASE: ote-webapp-mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3308
    ports:
      - 3308:3306
    volumes:
      - ~/ore-docker-volumes/ote/data/mysql-db:/var/lib/mysql
    restart: unless-stopped
